config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'
  get '/play', to: 'static_pages#play'

  get '/signup', to: 'users#new'
  get 'users/new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users
  resources :games

  post '/play_game', to: 'games#play'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :winnerID, presence: true
end

app/models/play_game.rb
class PlayGame < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :games, dependent: :destroy
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true

  validates :password, presence: true, length: { minimum: 6 }

  has_secure_password

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost

    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

  def logged_in_user
    return if logged_in?

    flash[:danger] = 'Please log in.'
    redirect_to login_url, status: :see_other
  end
end

app/controllers/games_controller.rb
require_relative '../helpers/load_drop_dead'

class GamesController < ApplicationController
  before_action :logged_in_user, only: %i[create play]

  def show
    @game = Game.find(params[:id])
  end

  def play
    sides = params[:sides]
    dice_count = params[:dice_count]
    player_count = params[:player_count]
    puts("SIDES~~~~~~~~~~~~~~~~~~~ #{sides.blank?}")

    if sides.blank? || dice_count.blank? || player_count.blank?
      puts("222222222SIDES~~~~~~~~~~~~~~~~~~~ #{sides.blank?}")
      flash.now[:danger] = 'invalid input, please input a number for each field'
      render 'static_pages/play', status: :unprocessable_entity
      return
    end

    @playGame = AutoDropDead.new
    @results = @playGame.play_game(sides.to_i, dice_count.to_i, player_count.to_i)
    create
  end

  def create
    @game = current_user.games.build(winnerID: @results[:winnerID].to_i, winningScore: @results[:winningScore].to_i,
                                     playerID: session[:id].to_i, settings: "#{params[:sides]},#{params[:dice_count]},#{params[:player_count]}")

    if @game.save
      flash[:success] = 'Game over!'
      redirect_to @game
    else
      flash[:danger] = 'Failure'
      render 'static_pages/home', status: :unprocessable_entity
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user.nil?
      flash.now[:danger] = 'There is no user with that account, please signup'
      render 'new', status: :unprocessable_entity
    elsif user&.authenticate(params[:session][:password])
      reset_session
      log_in user
      flash[:success] = 'Welcome Back!'
      redirect_to user
    else
      flash.now[:danger] = 'Invalid password'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def play
    @game = current_user.games.build if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @games = @user.games.paginate(page: params[:page])
  end

  def create
    @user = User.new(user_params)
    if @user.save
      reset_session
      log_in @user
      flash[:success] = 'Welcome to DropDeadRails!'
      redirect_to @user
    else
      render 'new', status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/DieClass.rb
class Die
  @numSides

  # initalize the number of side
  def initialize(numSides)
    @numSides = numSides
  end

  # generate a random number from 1 to numSides
  def RollDie
    1 + rand(@numSides)
  end
end

app/helpers/PlayerClass.rb
class Player
  attr_accessor :score, :isAlive, :pid

  # Initialize the player with inputted parameters, 0 score, and as being alive
  def initialize(numDice, die, pid)
    @numDice = numDice
    @die = die
    @pid = pid

    @score = 0
    @isAlive = true
  end

  # Roll remaining dice
  def RollDice
    sumForRoll = 0
    rolledBad = false

    # Loop numDice times and generate a random number for each
    for i in 0..@numDice - 1 do
      result = @die.RollDie()
      puts("die #{i + 1}: #{result}")

      # If the result of the dice is 2 or 5, subtract one of the die, and trigger the rolledBad flag
      if [2, 5].include?(result)
        @numDice -= 1
        rolledBad = true
      else # if the result isn't a 2 or 5 add it to current roll sum
        sumForRoll += result
      end
    end

    # if we didn't roll a bad number, add the roll sum to total score
    @score += sumForRoll if rolledBad == false

    # If the player is out of dice, toggle the alive flag
    return unless @numDice <= 0

    @isAlive = false
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def full_title(page_title = '')
        base_title = "DropDeadRails"
        if page_title.empty?
            base_title
        else
            "#{page_title} | #{base_title}"
        end
    end
end

app/helpers/games_helper.rb
module GamesHelper
  def winner(winnerID)
    return 'You' if winnerID == 1

    "Player #{winnerID}"
  end
end

app/helpers/load_drop_dead.rb
require_relative 'DieClass'
require_relative 'PlayerClass'

class AutoDropDead
  def play_game(sides, dice_count, player_count)
    activePlayers = []
    deadPlayers = []

    # Create the die
    commonDie = Die.new(sides)

    # Create the players
    (1..player_count).each do |i|
      i -= 1
      activePlayers.push(Player.new(dice_count, commonDie, i + 1))
    end

    # main game loop
    turnCounter = 1
    while activePlayers.length.positive?
      # puts("~~~~~~~~ Turn #{turnCounter} ~~~~~~~~~~~~")

      # Loop through remaining players and have them roll their dice
      (1..activePlayers.length).each do |i|
        i -= 1
        # puts("Player #{activePlayers[i].pid}")
        activePlayers[i].RollDice()
        # puts("Current Score: #{activePlayers[i].score}\n\n")
      end

      # Go through the remaining players and remove any dead players from the active list
      alivePlayers = []
      activePlayers.each do |player|
        if player.isAlive == false
          deadPlayers.push(player)
          # puts("Player #{player.pid} has dropped dead.")
        else
          alivePlayers.push(player)
        end
      end
      activePlayers = alivePlayers

      # Increment the turn counter
      turnCounter += 1
    end

    # Print the results
    # puts("\n~~~~~~~~~~ Results ~~~~~~~~~~~~")
    deadPlayers = deadPlayers.sort_by(&:pid) # sort the players by pid
    winningPlayer = nil
    # Loop through dead players to show their score and find the player with the highest score
    deadPlayers.each do |player|
      # puts("Player #{player.pid} score: #{player.score}")

      if winningPlayer.nil?
        winningPlayer = player
      elsif winningPlayer.score < player.score
        winningPlayer = player
      end
    end

    # display winning player
    # puts("\nPlayer #{winningPlayer.pid} wins!!!")
    { winnerID: winningPlayer.pid, winningScore: winningPlayer.score }
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    reset_session
    @current_user = nil
  end

  def current_user
    return unless session[:user_id]

    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    size = options[:size]
    gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag('default_profile.png', alt: user.name, class: 'gravatar', width: size.to_s + 'px')
  end
end

app/views/games/_game.html.erb
<li id="game-<%= game.id%>">
    <span class="user"><%= link_to game.user.name%></span>
    <span class="timestamp">
        Played <%= time_ago_in_words(game.created_at) %> ago.
    </span>

    <span class="winner"><%= winner game.winnerID %> won</span>
    <span class="score">with a score of <%= game.winningScore %>.</span>
    <%= link_to "view game", game %>
</li>

app/views/games/show.html.erb
<% provide(:title, "Game #{@game.id}") %>

<div class="center">
    <div class="row">
        <div class="col-md-12">
            <h1> Game <%= @game.id %> </h1>
            <%= winner @game.winnerID %> won the game with a score of <%= @game.winningScore %>
            </br>
            settings used: <%= @game.settings %>
        </div>
    </div>
    <div class="row center">
        <%= link_to "Change Parameters", play_path, class: "btn btn-lg btn-primary" %>
        <% @settings = @game.settings.split(',')%>
        <%= link_to "Play Again", play_game_path(sides: @settings[0], dice_count: @settings[1], player_count: @settings[2]), data: {turbo_method: :post}, class: "btn btn-lg btn-primary" %>
    </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        Drop Dead Rails by Eric Morse
    </small>
    <nav>
        <ul>
            <li> <%= link_to "About" , about_path %> </li>
        </ul>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
        <%= link_to "DropDeadRails", root_path, id: "logo" %>
        <nav>
            <div class="navbar-header">
                <button id="hamburger" type="button" class="navbar-toggle collapsed">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <ul id="navbar-menu" class="nav navbar-nav navbar-right collapse navbar-collapse">
                <li><%= link_to "Home", root_path %></li>

                <% if logged_in? %>
                <li class='dropdown'>
                    <a href="#" id="account" class="dropdown-toggle">
                        Account <b class="caret"></b>
                    </a>
                    <ul id="dropdown-menu" class="dropdown-menu">
                        <li><%= link_to "Profile", current_user %></li>
                        <li class="divider"></li>
                        <li>
                            <%= link_to "Log out", logout_path, data: {"turbo-method": :delete} %>
                        </li>
                    </ul>
                </li>
                <% else %>
                <li><%= link_to "Login", login_path %></li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
    </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">

    <%= render "layouts/rails_default" %>
    <%= render "layouts/shim" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <%= render "layouts/header" %>
    <div class="container">
        <%= render "shared/flash_messages" %>
        <%= yield %>
        <%= render "layouts/footer" %>
        <%= debug(params) if Rails.env.development? %>
    </div>
</body>

</html>

app/views/shared/_error_messages.html.erb
 <% if @user.errors.any? %>
 <div id="error_explanation">
     <div class="alert alert-danger">
         The form contains <%= pluralize(@user.errors.count, "error") %>.
     </div>
     <ul>
         <% @user.errors.full_messages.each do |msg| %>
         <li><%= msg %></li>
         <% end %>
     </ul>
 </div>
 <% end %>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1> About </h1>
<p>
    Eric Morse is a 5th year software engineering student, and created this webapp to play the drop dead dice game for CIS3260 A2.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>DropDeadRails</h1>
    <h2>
        This is the home page for the
        <a href="https://dropdeadrails.onrender.com/"> Drop Dead Rails Program</a>
        for assignment 2 developed by Eric Morse.
    </h2>

    <% if logged_in?%>
    <%= link_to "Play Game!", play_path, class: "btn btn-lg btn-primary" %>
    <% else %>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <% end %>
</div>

app/views/static_pages/play.html.erb
<% provide(:title, "Play") %>

<%= form_with(model: @play_game, url: play_game_path) do |f|%>
<div class="sides">
    <%= f.label :sides %>
    <%= f.number_field :sides, class: 'form-control' %>
    <%= f.label :dice_count %>
    <%= f.number_field :dice_count, class: 'form-control' %>
    <%= f.label :player_count %>
    <%= f.number_field :player_count, class: 'form-control' %>
</div>
<%= f.submit "Play!", class: "btn btn-primary"%>
<% end %>

app/views/users/new.html.erb
 <% provide(:title, 'Sign up') %>
 <h1>Sign up</h1>

 <div class="row">
     <div class="col-md-6 col-md-offset-3">
         <%= form_with(model: @user) do |field| %>
         <%= render 'shared/error_messages' %>

         <%= field.label :name %>
         <%= field.text_field :name, class: 'form-control' %>

         <%= field.label :email %>
         <%= field.email_field :email, class: 'form-control' %>

         <%= field.label :password %>
         <%= field.password_field :password, class: 'form-control' %>
         <%= field.label :password_confirmation, "Confirm Password" %>

         <%= field.password_field :password_confirmation, class: 'form-control' %>
         <%= field.submit "Create my account", class: "btn btn-primary" %>
         <% end %>
     </div>
 </div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
    </aside>
    <div class="col-md-8">
        <h3>Game History (<%= @user.games.count %> games)</h3>
        <% if @user.games.any? %>
        <ul>
            <%= render @games%>
        </ul>
        <%= will_paginate @games%>
        <% end %>
    </div>
</div>

<div class="row center">
    <%= link_to "Play Game!", play_path, class: "btn btn-lg btn-primary" %>
    <%= link_to "Log Out", logout_path, data: {"turbo-method": :delete}, class: "btn btn-lg btn-primary" %>
</div>